apiVersion: 1

# Warning! Do not change name: it will duplicate data sources
datasources:
  - name: VictoriaMetrics
    orgId: 1
    isDefault: true
    type: prometheus
    access: proxy
    url: http://victoria-metrics:8428
